version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=nestjs_auth
    ports:
      - "5432:5432"
    volumes:
      - './data/db:/var/lib/postgresql/data'